// lib/services/habit_service.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:getsetgo/models/habit.dart';
import 'package:getsetgo/models/habit_entry.dart';

class HabitService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  User? get currentUser => _auth.currentUser;

  // Method to add a new habit
  // CORRECTED: Now returns the Firestore document ID (String)
  Future<String> addHabit(Habit habit) async {
    if (currentUser == null) {
      throw Exception("User not logged in.");
    }
    // Ensure the habit's userId is set to the current user's ID
    final habitToAdd = habit.copyWith(userId: currentUser!.uid);
    final DocumentReference docRef = await _firestore.collection('habits').add(habitToAdd.toFirestore());
    return docRef.id; // Return the ID generated by Firestore
  }

  // Method to update an existing habit
  Future<void> updateHabit(Habit habit) async {
    if (currentUser == null) {
      throw Exception("User not logged in.");
    }
    // Ensure the habit's userId matches the current user's ID for security
    if (habit.userId != currentUser!.uid) {
      throw Exception("Unauthorized: Cannot update another user's habit.");
    }
    // Ensure habit.id is not null before using it
    if (habit.id == null || habit.id!.isEmpty) {
      throw Exception("Habit ID is missing for update operation.");
    }
    // Corrected: Use habit.toFirestore() for updating
    await _firestore.collection('habits').doc(habit.id).update(habit.toFirestore());
  }

  // Method to delete a habit
  Future<void> deleteHabit(String habitId) async {
    if (currentUser == null) {
      throw Exception("User not logged in.");
    }
    // Before deleting, optionally verify that the habit belongs to the current user
    // This is good practice for security rules, but also helpful here.
    final habitDoc = await _firestore.collection('habits').doc(habitId).get();
    if (!habitDoc.exists || habitDoc.data()?['userId'] != currentUser!.uid) {
      throw Exception("Unauthorized: Cannot delete another user's habit or habit does not exist.");
    }
    await _firestore.collection('habits').doc(habitId).delete();
  }

  // Method to get a stream of habits for the current user
  Stream<List<Habit>> getHabitsStream() {
    if (currentUser == null) {
      // Return an empty stream if no user is logged in
      return Stream.value([]);
    }
    return _firestore
        .collection('habits')
        .where('userId', isEqualTo: currentUser!.uid)
        .orderBy('startDate', descending: false)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => Habit.fromFirestore(doc))
            .where((habit) => habit.userId == currentUser!.uid) // Double check client side
            .toList());
  }

  // --- Methods for Habit Entries ---

  // Method to add a new habit entry for a specific date
  Future<void> addOrUpdateHabitEntry(HabitEntry entry) async {
    if (currentUser == null) {
      throw Exception("User not logged in.");
    }
    // Query for an existing entry for the same habitId, userId, and date
    final existingEntryQuery = await _firestore.collection('habit_entries')
      .where('habitId', isEqualTo: entry.habitId)
      .where('userId', isEqualTo: currentUser!.uid)
      .where('date', isEqualTo: Timestamp.fromDate(DateTime(entry.date.year, entry.date.month, entry.date.day))) // Normalize date for query
      .limit(1)
      .get();

    if (existingEntryQuery.docs.isNotEmpty) {
      // Update existing entry
      final docId = existingEntryQuery.docs.first.id;
      await _firestore.collection('habit_entries').doc(docId).update(entry.toFirestore());
    } else {
      // Add new entry
      await _firestore.collection('habit_entries').add(entry.toFirestore());
    }
  }

  // Method to get a stream of habit entries for a specific habit
  Stream<List<HabitEntry>> getHabitEntriesStream(String habitId) {
    if (currentUser == null) {
      return Stream.value([]);
    }
    return _firestore
        .collection('habit_entries')
        .where('habitId', isEqualTo: habitId)
        .where('userId', isEqualTo: currentUser!.uid)
        .orderBy('date', descending: true) // Order by date, newest first
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => HabitEntry.fromFirestore(doc))
            .toList());
  }

  // Method to get habit entries for a specific range (e.g., for graphs)
  Stream<List<HabitEntry>> getHabitEntriesForDateRange(String habitId, DateTime startDate, DateTime endDate) {
    if (currentUser == null) {
      return Stream.value([]);
    }
    // Normalize dates to start of day for accurate range query
    final normalizedStartDate = DateTime(startDate.year, startDate.month, startDate.day);
    final normalizedEndDate = DateTime(endDate.year, endDate.month, endDate.day, 23, 59, 59); // End of day

    return _firestore
        .collection('habit_entries')
        .where('habitId', isEqualTo: habitId)
        .where('userId', isEqualTo: currentUser!.uid)
        .where('date', isGreaterThanOrEqualTo: Timestamp.fromDate(normalizedStartDate))
        .where('date', isLessThanOrEqualTo: Timestamp.fromDate(normalizedEndDate))
        .orderBy('date', descending: false)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => HabitEntry.fromFirestore(doc))
            .toList());
  }
}