// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUZnVzyhtb5P5X7IPfFcf280-fXGM-kD4',
    appId: '1:693815159959:web:4a4f3b03eeff5cc6db8dd2',
    messagingSenderId: '693815159959',
    projectId: 'react-native-tracker-d99aa',
    authDomain: 'react-native-tracker-d99aa.firebaseapp.com',
    storageBucket: 'react-native-tracker-d99aa.firebasestorage.app',
    measurementId: 'G-CVH5XS5RN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa27nJWqGRDCe-XEeiP6YYdnfXhTzCs6Q',
    appId: '1:693815159959:android:a9456a37c114082adb8dd2',
    messagingSenderId: '693815159959',
    projectId: 'react-native-tracker-d99aa',
    storageBucket: 'react-native-tracker-d99aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSCkb6ZZTKSeKCHzVewdnHlHNZKlXCNg0',
    appId: '1:693815159959:ios:bf4b6c77d03501b5db8dd2',
    messagingSenderId: '693815159959',
    projectId: 'react-native-tracker-d99aa',
    storageBucket: 'react-native-tracker-d99aa.firebasestorage.app',
    iosBundleId: 'com.example.getsetgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSCkb6ZZTKSeKCHzVewdnHlHNZKlXCNg0',
    appId: '1:693815159959:ios:bf4b6c77d03501b5db8dd2',
    messagingSenderId: '693815159959',
    projectId: 'react-native-tracker-d99aa',
    storageBucket: 'react-native-tracker-d99aa.firebasestorage.app',
    iosBundleId: 'com.example.getsetgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUZnVzyhtb5P5X7IPfFcf280-fXGM-kD4',
    appId: '1:693815159959:web:f5eabf3e8e07c49adb8dd2',
    messagingSenderId: '693815159959',
    projectId: 'react-native-tracker-d99aa',
    authDomain: 'react-native-tracker-d99aa.firebaseapp.com',
    storageBucket: 'react-native-tracker-d99aa.firebasestorage.app',
    measurementId: 'G-GW6WQFFMJL',
  );
}
